trigger:
- master

pool:
  vmImage: 'Ubuntu-16.04'

variables:
  imageName: 'shregistry/bootcamp-demo'

steps:
- task: Docker@2
  displayName: Build and push image
  inputs:
    containerRegistry: shregistry
    repository: $(imageName)
    command: buildAndPush
    Dockerfile: app/Dockerfile

