trigger:
- master

pool:
  vmImage: 'Ubuntu-16.04'

variables:
  imageName: 'bootcamp-demo'

steps:
- task: Docker@2
  displayName: Build and push image
  inputs:
    containerRegistry: usharegistry
    repository: $(imageName)
    command: buildAndPush
    Dockerfile: app/Dockerfile

